### ISSUE TITLE
'pkg_resources' error

### ISSUE THREAD

**Issue by roshanravan** [BlackFoxTM/FoxCC#4]
I get this error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Fox-CC/cc.py", line 5, in <module>
    from pyfiglet import Figlet
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyfiglet/__init__.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by roshanravan** [comment]
I fixed this error by installing the setuptools package in Termux. 

```
pip install setuptools
```
&
```
pip install --upgrade pip
```
